### ISSUE TITLE
Segmentation fault fleXdLoggerServer

### ISSUE THREAD

**Issue by AdrianPeniakGL** [FleX-d/LTD#3]
Fresh installation not works 
```
peniak@debian:~/FleX-d/git/LTD/build$ ./apps/fleXdLoggerServer/fleXdLoggerServer 
[FleXdLoggerServer][1528477278328][INFO] :  -> Init
Segmentation fault
```

here is back-trace:
```
peniak@debian:~/FleX-d/git/LTD/build$ ./seg_wrapper.sh ./apps/fleXdLoggerServer/fleXdLoggerServer 
[FleXdLoggerServer][1528477760042][INFO] :  -> Init
./seg_wrapper.sh: line 3: 25795 Segmentation fault      (core dumped) "$@"
Reading symbols from ./apps/fleXdLoggerServer/fleXdLoggerServer...done.

warning: core file may not match specified executable file.
[New LWP 25795]
Core was generated by `./apps/fleXdLoggerServer/fleXdLoggerServer'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0xb7450508 in _IO_vfprintf_internal (s=s@entry=0x85a7340, format=<optimized out>, format@entry=0x806d5a4 "[%s][%ld][%s] %s ", ap=0xbf8f8c34 "\354rZ\b\314rZ\b\207\276l\267\004sZ\b>\325\006\b", ap@entry=0xbf8f8c28 "\004sZ\b*\272_\340c\001") at vfprintf.c:1642
1642    vfprintf.c: No such file or directory.
/home/peniak/backtrace: No such file or directory.
(gdb) where
#0  0xb7450508 in _IO_vfprintf_internal (s=s@entry=0x85a7340, format=<optimized out>, format@entry=0x806d5a4 "[%s][%ld][%s] %s ", ap=0xbf8f8c34 "\354rZ\b\314rZ\b\207\276l\267\004sZ\b>\325\006\b", ap@entry=0xbf8f8c28 "\004sZ\b*\272_\340c\001") at vfprintf.c:1642
#1  0xb74f2177 in __GI___vsyslog_chk (pri=<optimized out>, pri@entry=4, flag=flag@entry=-1, fmt=fmt@entry=0x806d5a4 "[%s][%ld][%s] %s ", ap=ap@entry=0xbf8f8c28 "\004sZ\b*\272_\340c\001") at ../misc/syslog.c:220
#2  0xb74f2267 in __syslog (pri=4, fmt=0x806d5a4 "[%s][%ld][%s] %s ") at ../misc/syslog.c:117
#3  0x08064c79 in flexd::logger::FleXdLoggerServer::writeLog (this=0x85a70b8, appName="FleXdLoggerServer", time=0, priority="INFO", message=" -> Init") at /home/peniak/FleX-d/git/LTD/apps/fleXdLoggerServer/src/FleXdLoggerServer.cpp:100
#4  0x080645ea in flexd::logger::FleXdLoggerServer::FleXdLoggerServer (this=0x85a70b8, poller=..., logToDlt=false) at /home/peniak/FleX-d/git/LTD/apps/fleXdLoggerServer/src/FleXdLoggerServer.cpp:44
#5  0x08068122 in std::make_unique<flexd::logger::FleXdLoggerServer, flexd::icl::ipc::FleXdEpoll&, bool&> () at /usr/include/c++/4.9/bits/unique_ptr.h:765
#6  0x08067ef2 in main (argc=1, argv=0xbf8f8e34) at /home/peniak/FleX-d/git/LTD/apps/fleXdLoggerServer/src/mainFleXdLogger.cpp:76
(gdb) 

```
please fix this issue immediately!!!

**Comment by AdrianPeniakGL** [comment]
Fixed with [commit](https://github.com/FleX-d/LTD/commit/49bac8b98c1da6f4f13d94821f66ef6c46e543f8), issue was related to 32 bit machines.

Thank you for support .....
